### ISSUE TITLE
Отступы и выравнивания

### ISSUE THREAD

**Issue by truenorthpaul** [Shih-tzuco/TitleCapitalizationTool#12]
Любой код помещенный в фигурные скобки (кроме ситуаций, когда разрешается записывать оператор и скобки в одну строку) должен обладать отступом в 4 пробела от уровня сдвига самих скобок, к которым он относится. Если скобки относятся к какой-либо управляющей конструкции (`if`, `for`, `while` и т. д.), то фигурные скобки должны быть выравнены в соответствии с данной конструкцией.

Методы, в которых данное правило не соблюдается:
- `TitleCapitalizationTool.MainClass.Main`.

**Comment by Shih-tzuco** [comment]
I HOPe now is Correct!
